Traceback (most recent call last):
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Generate a sequence of points to predict
t_extrapolated = torch.linspace(20, 40, 1000)
hidden = rnn.initHidden()
output_seq = []

rnn.eval() # Set the model to evaluation mode

t_pred = []
t0 = 100
for i in range(t0):
    output, hidden = rnn(sine_wave[i].unsqueeze(0), hidden)

prev_output = output
actual_seq = []
for i in range(len(t_extrapolated)):
    output, hidden = rnn(prev_output, hidden)
    output_seq.append(output)
    prev_output = output
    t_pred.append(t_extrapolated[i])
    if i + 1 + t0 < len(sine_wave):
    actual_seq.append(sine_wave[i+1 + t0].item())

output_seq = [o.item() for o in output_seq]
print(len(output_seq), len(actual_seq))
plt.plot(t_pred, output_seq, label='RNN prediction')
plt.plot(t_pred[:len(actual_seq)], actual_seq, label='Actual')
plt.legend()
plt.title('RNN Sine Wave Prediction')
plt.xlabel('Time')
plt.ylabel('Value')
plt.show()
------------------


[0;36m  Cell [0;32mIn[6], line 21[0;36m[0m
[0;31m    actual_seq.append(sine_wave[i+1 + t0].item())[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m expected an indented block after 'if' statement on line 20


